// import '../assets/iconfont';
import Layout from './layout';
import Button from './button';
import Dialog from './dialog';
import Draggable from './draggable';
import Resizable from './resizable';
import Table from './table';
import CenterBox from './centerbox';
import Input from './input';
import Select from './select';
import Tree from './tree';
import ComboTree from './combotree';
import Icon from './icon';
import CheckBoxGroup from './checkboxgroup';
import CheckBox from './checkbox';
import RadioGroup from './radiogroup';
import Radio from './radio';
const LyUI = {
    install: function (Vue) {
        let cName = 'Ly';
        Vue.component(cName + 'Layout', Layout);
        Vue.component(cName + 'Layout.Panel', Layout.Panel);
        Vue.component(cName + 'LayoutPanel', Layout.Panel);
        Vue.component(cName + 'Button', Button);
        Vue.component(cName + 'Dialog', Dialog);
        Vue.component(cName + 'Draggable', Draggable);
        Vue.component(cName + 'Resizable', Resizable);
        Vue.component(cName + 'Table', Table);
        Vue.component(cName + 'CenterBox', CenterBox);
        Vue.component(cName + 'Input', Input);
        Vue.component(cName + 'Select', Select);
        Vue.component(cName + 'Select.Option', Select.Option);
        Vue.component(cName + 'Option', Select.Option);
        Vue.component(cName + 'Tree', Tree);
        Vue.component(cName + 'ComboTree', ComboTree);
        Vue.component(cName + 'Icon', Icon);
        Vue.component(cName + 'CheckBoxGroup', CheckBoxGroup);
        Vue.component(cName + 'CheckBox', CheckBox);
        Vue.component(cName + 'RadioGroup', RadioGroup);
        Vue.component(cName + 'Radio', Radio);
    }
};
export default LyUI;